### ISSUE TITLE
[Question] Exporting annotations / images in specific format

### ISSUE THREAD

**Issue by M-Asad-Bin-Hameed** [autodistill/autodistill#10]
Is there an option to export the auto-annotated image annotations in a specific output format? say coco / yolo / voc etc.

**Comment by SkalskiP** [comment]
Hi @M-Asad-Bin-Hameed 👋🏻 !

I noticed that you are talking about supervision. Let me clarify a few things:
- Supervision supports loading and saving in PASCAL VAC and YOLO formats. Both boxes and segmentations. We will work on adding support for more dataset formats.
- You can load datasets with [from_yolo](https://roboflow.github.io/supervision/dataset/core/#supervision.dataset.core.DetectionDataset.from_yolo) and [from_pascal_voc](https://roboflow.github.io/supervision/dataset/core/#supervision.dataset.core.DetectionDataset.from_pascal_voc), and save with [as_yolo](https://roboflow.github.io/supervision/dataset/core/#supervision.dataset.core.DetectionDataset.as_yolo) and [as_pascal_voc](https://roboflow.github.io/supervision/dataset/core/#supervision.dataset.core.DetectionDataset.as_pascal_voc).
- If you require support for different formats, feel free to submit an issue with a feature request [here](https://github.com/roboflow/supervision/issues).

**Comment by M-Asad-Bin-Hameed** [comment]
Thank you both @yeldarby  @SkalskiP. Did not realize it was supervision in the background for this stuff. Got the idea of how to work with it now.
