### ISSUE TITLE
if the target object does not perform well in the base model

### ISSUE THREAD

**Issue by bankxi** [autodistill/autodistill#103]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question

If the target object does not perform well in the detection performance of the base model, is it impossible to train the target model?

**Comment by capjamesg** [comment]
Hello there! Autodistill lets you use foundation models to auto-label data. If a base model is unable to detect your object of interest, Autodistill will be unable to create a labeled dataset with which you can train a model.

Our supported base models, among which are state-of-the-art models like Grounding DINO and CLIP, are able to detect a wide range of objects, from boxes to vinyl records. With that said, foundation models cannot identify any objects, particularly obscure or specific objects (i.e. a particular kind of defect on a product).

**Comment by capjamesg** [comment]
I am going to close this issue since there has been no further comment. If you have any questions, let me know and we can re-open the issue!
