### ISSUE TITLE
Link Download milk.zip error

### ISSUE THREAD

**Issue by andiplanplan2** [autodistill/autodistill#116]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar bug report.

### Bug

Good day. i am facing an error regarding to milk.zip dataset which provided in GColab tutorial file. 
Last week (Jan 12th 2024), i tried to run the tutorial file and it worked well.
Unfortunately, today, the tutorial is resulting error output which stated that the dataset is corrupt.

![image](https://github.com/autodistill/autodistill/assets/15009487/2666c2fe-8dc6-46c3-b3a6-abc172d52215)

as you can see above, the milk.zip file is unable to be unzipped. hence i tried to download the file to local and tried to unzip manually, but resulted with the same output.
![image](https://github.com/autodistill/autodistill/assets/15009487/dce4c649-b9cf-4e14-a793-bf465de9f962)

would you mind to fix the link?

thanks in advance.
cheers.

### Minimal Reproducible Example

!mkdir {HOME}/videos
%cd {HOME}/videos

# download zip file containing videos
!wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1wnW7v6UTJZTAcOQj0416ZbQF8b7yO6Pt' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1wnW7v6UTJZTAcOQj0416ZbQF8b7yO6Pt" -O milk.zip && rm -rf /tmp/cookies.txt

# unzip videos
!unzip milk.zip 

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
Hello there! Can you please use:

```
!wget https://media.roboflow.com/milk.zip
```

I will replace the Google Drive text with the `media.roboflow.com` link above in the notebook but this wil take some time.

Let me know if you have any more questions!
