### ISSUE TITLE
basemodel.label() Different types of masks overlap

### ISSUE THREAD

**Issue by 6yuhao6** [autodistill/autodistill#117]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question

basemodel:GroundedSAM .Generate seg label file using the "basemodel.label()" command.
the label file as follows:
![Segerror](https://github.com/autodistill/autodistill/assets/157555643/2ca079c1-6656-4900-8254-71c2d0b7a98e)
I want the two categories to not overlap, what should I do

**Comment by SkalskiP** [comment]
Hi @6yuhao6 👋🏻 ! Is that question only about this specific image or in general?

**Comment by 6yuhao6** [comment]
> Hi @6yuhao6 👋🏻 ! Is that question only about this specific image or in general?

on my dataset is general.  Maybe it is because the target box generated overlaps, i guess.

**Comment by SkalskiP** [comment]
Yes. That's exactly the reason. We could still apply some post processing - try to cat to area of one mask from the other.
