### ISSUE TITLE
Segmentation fault raspberry pi 5 bookworm

### ISSUE THREAD

**Issue by pythonstuff8** [autodistill/autodistill#121]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar bug report.

### Bug

When I run my code I get segmentation fault what happened `WARNING: CUDA not available. GroundingDINO will run very slowly.
trying to load grounding dino directly
downloading dino model weights
torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:3526.)
final text_encoder_type: bert-base-uncased
tokenizer_config.json: 100%|##################| 28.0/28.0 [00:00<00:00, 167kB/s]
config.json: 100%|#############################| 570/570 [00:00<00:00, 3.74MB/s]
vocab.txt: 100%|#############################| 232k/232k [00:00<00:00, 2.13MB/s]
tokenizer.json: 100%|########################| 466k/466k [00:00<00:00, 3.83MB/s]
model.safetensors: 100%|#####################| 440M/440M [01:14<00:00, 5.93MB/s]
Labeling output/Suhaan_noisy0.jpg:   0%|                 | 0/10 [00:00<?, ?it/s]The `device` argument is deprecated and will be removed in v5 of Transformers.
Segmentation fault
`

### Environment

autodistill - 0.1.24 python 3.11 raspberry pi bookworm

### Minimal Reproducible Example

`from autodistill.detection import CaptionOntology

    ontology=CaptionOntology({
        f"{name}": f"{name}"

    })
    from autodistill_grounded_sam import GroundedSAM

    base_model = GroundedSAM(ontology=ontology)
    dataset = base_model.label(
        input_folder="output",
        extension=".jpg",
        output_folder="outputf")`

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
Hello there! How much RAM does your Pi have? I suspect you are seeing this error is for one of two reasons:

1. Your device does not hav enough RAM (Grounding DINO requires a few GB of RAM), or;
2. The model has not been developed for use with the Pi.

I usually run Grounding DINO either on my Mac or a machine with an NVIDIA GPU.

**Comment by pythonstuff8** [comment]
8gb

**Comment by pythonstuff8** [comment]
fixed by relinstallting all modules

**Comment by Jordan-Pierce** [comment]
@capjamesg Why is there not a way to write files when using the `base_model.label`? It seems like all images and results are being loaded into RAM and only writes after it's completed. But what if someone is working with a large dataset or has less RAM resources? Right now I'm having to do it in batches; am I missing something? Thanks.
