### ISSUE TITLE
!yolo task=segment predict ... - Task not available for YoloV8

### ISSUE THREAD

**Issue by a333klm** [autodistill/autodistill#134]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question

I followed this notebook and I got the expected results.
[How to auto train yolov8 model with autodistill](https://github.com/roboflow/notebooks/blob/main/notebooks/how-to-auto-train-yolov8-model-with-autodistill.ipynb)

But I want to run segmentation on the final video, not detection.
Instead of 
`!yolo predict model={TRAINED_MODEL_PATH} source={INPUT_VIDEO_PATH}`

I want
`!yolo task=segment predict model={TRAINED_MODEL_PATH} source={INPUT_VIDEO_PATH}`

But this task is not available and the generated video shows only the bounding boxes without the segmentation.

**Comment by capjamesg** [comment]
Thank you for creating this issue!

Did you update the `.train()` call to specify that you want to use the `yolov8n-seg` checkpoint for transfer learning?

```python
from autodistill_yolov8 import YOLOv8

target_model = YOLOv8("yolov8n-seg.pt")
target_model.train(DATA_YAML_PATH, epochs=50)
```

**Comment by a333klm** [comment]
Thanks for your time.
I selected the wrong model path:
It should be "segment" instead of "train".
`TRAINED_MODEL_PATH = f"{HOME}/runs/segment/train/weights/best.pt"`
The segment-model has task=segment :)
