### ISSUE TITLE
Add support for EVA-CLIP-18B

### ISSUE THREAD

**Issue by lab176344** [autodistill/autodistill#136]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Description

I want to add support for https://github.com/baaivision/EVA/tree/master/EVA-CLIP-18B#summary-of-eva-clip-performance. It vastly outperforms open clip and openai' CLIP

### Use case

For classification and combination models

### Additional

I want to make sure somebody from the community is not working on this. Please comment here and give a go ahead 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by lab176344** [comment]
@capjamesg if you can confirm this that will be great

**Comment by capjamesg** [comment]
Thank you for creating this Issue! We don't currently support EVA-CLIP. Feel free to create this module!

**Comment by capjamesg** [comment]
@lab176344 Following up to see if you are still interested in working on this!

**Comment by lab176344** [comment]
@capjamesg I think we already added this I guess

**Comment by capjamesg** [comment]
Ah, of course! In that case, I will close this issue. Thank you for your contribution!

Link for reference to anyone reading: https://github.com/lab176344/autodistill-evaclip

**Comment by lab176344** [comment]
@capjamesg Is any one working on PaliGemma? Would like to add support

**Comment by capjamesg** [comment]
We have a project in the works that will be released on Monday :D

We will have support as a base model on Monday, and fine-tuning likely later in the week.

We would also love support for Gemini Flash for classification (https://deepmind.google/technologies/gemini/flash/), but we aren't actively working on that. If that interests you, feel free to file a PR!

**Comment by lab176344** [comment]
okay cool will take it up
