### ISSUE TITLE
Add T-Rex2 Model

### ISSUE THREAD

**Issue by Pro100rus32** [autodistill/autodistill#147]
Repo: https://github.com/IDEA-Research/T-Rex
Demo: https://huggingface.co/spaces/Mountchicken/T-Rex2

**Comment by yeldarby** [comment]
Is this model actually usable? The code calls a remote API and says to contact them to request access.

**Comment by Jordan-Pierce** [comment]
It's not; they refuse to open-source the model. See their Issues tab on the repo.

**Comment by capjamesg** [comment]
Since we can't use this model, I am going to close this issue. If anything changes, we can re-open this issue and begin work. It would be amazing to have T-Rex in Autodistill if the model were open 😊
