### ISSUE TITLE
Add Gemini Flash Support for classification 

### ISSUE THREAD

**Issue by lab176344** [autodistill/autodistill#156]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Description

Adding base model Gemini Flash for classificaiton

### Use case

classification

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
Thank you for creating this Issue! Let us know when you have made the project!

**Comment by lab176344** [comment]
@capjamesg I saw there is a project https://github.com/autodistill/autodistill-gemini already with gemini Should I update the documentation to reflect his or what should be done here

**Comment by capjamesg** [comment]
Hello @lab176344! It would be great if you updated the existing one and added a flag where users can choose what model they want to use. We will also need docs in the README that explains how to choose a model, and what models are available.

**Comment by lab176344** [comment]
ok cool thank you will raise a PR in both soon
