### ISSUE TITLE
Is autodistill_yolov8 using cpu as default?

### ISSUE THREAD

**Issue by HAOHANZHOU** [autodistill/autodistill#158]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question

I am using jupyter notebook. YOLOv8 in autodistill_yolov8 uses CPUwhen training, but YOLO in Ultralytics uses GPU.
![q1](https://github.com/autodistill/autodistill/assets/54381714/a50c2a40-bd0d-49fd-af27-d81e23c4a650)
![q2](https://github.com/autodistill/autodistill/assets/54381714/469a7a1c-2ce9-4332-9fc4-7af3ec16236a)

**Comment by capjamesg** [comment]
Thank you for opening this issue. By default, Autodistill YOLOv8 uses the CPU. You can pass in your own device by using:

```
target_model.train("data.yaml", device=0)
```

Here, `0` corresponds with `cuda:0`.
