### ISSUE TITLE
Error in import supervision as sv

### ISSUE THREAD

**Issue by elpabos** [autodistill/autodistill#17]
Exception has occurred: AttributeError
partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)
  File "/workspace/code/images_generation.py", line 2, in <module>
    import supervision as sv
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)

**Comment by SkalskiP** [comment]
Hi @elpabos 👋🏻! Looks like the problem originated from cv2 package. Do you experience that problem in our notebook or in your local environment?

**Comment by elpabos** [comment]
It was in my local environment. Finally, I solved it using CUDA Version 12. 
Thanks

**Comment by yeldarby** [comment]
Glad you got it sorted out!
