### ISSUE TITLE
Filtering the detection

### ISSUE THREAD

**Issue by Rahul-Pi** [autodistill/autodistill#22]
I am using GroundedSAM to label e-scooters using 
`base_model.label(input_folder="./images",  output_folder="./dataset")`

however with
`ontology = CaptionOntology({
    "electric scooter": "e-scooter",
})` it does not seem to work on all images.

But modifying this to `ontology = CaptionOntology({
    "e-scooter": "e-scooter",
    "electric scooter": "e-scooter",
    "kick scooter": "e-scooter",
})` increases the detection rate.

However this results in the same object having multiple labels. I was wondering if there is any way I can avoid getting multiple detections for the same object?

An ugly way I went about it is to extract the [detections](https://github.com/autodistill/autodistill/blob/main/autodistill/detection/detection_base_model.py#L41) and compare the overlap between the masks, then keep the one with the highest confidence. But this results in the datatype to change and thereby subsequent code all requiring modification.

**Comment by capjamesg** [comment]
Hello @Rahul-Pi! Thank you for this note. The `supervision.non_max_suppression` function (https://roboflow.github.io/supervision/detection/utils/#non_max_suppression) may be helpful in filtering out duplicate detections.

@yeldarby Should we do NMS by default on object detection results?

**Comment by SkalskiP** [comment]
@capjamesg you can also call [`.with_nms`](https://roboflow.github.io/supervision/detection/core/#supervision.detection.core.Detections.with_nms) on `detections`.

**Comment by Rahul-Pi** [comment]
Thank you @capjamesg and @SkalskiP 

Using `base_model.predict(test_image).with_nms(threshold=0.85, class_agnostic=True)` solved the problem.

Would it be possible to have this as an argument in the [DetectionBaseModel.label](https://github.com/autodistill/autodistill/blob/main/autodistill/detection/detection_base_model.py#L23)?

Should I create a PR with this change?

**Comment by SkalskiP** [comment]
> Using `base_model.predict(test_image).with_nms(threshold=0.85, class_agnostic=True)` solved the problem.

So awesome to hear that! 🔥

**Comment by yeldarby** [comment]
> @yeldarby Should we do NMS by default on object detection results?

Yes, I think we should.

**Comment by O-J1** [comment]
My apolgoies for necroing this but is it possible to apply this to GroundedSAM through AutoDistill? I dont want to feed Yolo bad segementation masks and ideally less tedious work is better
