### ISSUE TITLE
[Question] How to export model weights (e.g distilled yolov5)

### ISSUE THREAD

**Issue by cadrev** [autodistill/autodistill#26]
Hello, is there a way to download the model weights for the distilled model?

**Comment by capjamesg** [comment]
Hello @cadrev! Your weights will be saved to the directory in which you run Autodistill. All training is done on your machine, so you don't need to download the weights for your distilled model from anywhere. For YOLOv5, for example, your weights should be in a folder called `runs` that is generated after training.
