### ISSUE TITLE
ImportError: cannot import name 'DetectionOntology' from 'autodistill.detection' (/mnt/scratch/sibo/autodistill/autodistill/detection/__init__.py)

### ISSUE THREAD

**Issue by sibozhang** [autodistill/autodistill#30]
python code:
from autodistill_grounding_dino import GroundingDINO
from autodistill.detection import CaptionOntology

Traceback (most recent call last):
  File "label_visualize.py", line 8, in <module>
    from autodistill_grounding_dino import GroundingDINO
  File "/mnt/home/sibo/.conda/envs/autodistill/lib/python3.7/site-packages/autodistill_grounding_dino/__init__.py", line 1, in <module>
    from autodistill_grounding_dino.grounding_dino_model import GroundingDINO
  File "/mnt/home/sibo/.conda/envs/autodistill/lib/python3.7/site-packages/autodistill_grounding_dino/grounding_dino_model.py", line 17, in <module>
    from autodistill.detection import CaptionOntology, DetectionBaseModel
  File "/mnt/scratch/sibo/autodistill/autodistill/detection/__init__.py", line 1, in <module>
    from autodistill.detection.caption_ontology import CaptionOntology
  File "/mnt/scratch/sibo/autodistill/autodistill/detection/caption_ontology.py", line 4, in <module>
    from autodistill.detection import DetectionOntology
ImportError: cannot import name 'DetectionOntology' from 'autodistill.detection' (/mnt/scratch/sibo/autodistill/autodistill/detection/__init__.py)

**Comment by ccly1996** [comment]
same problem

**Comment by dFuong** [comment]
same problem, too

**Comment by capjamesg** [comment]
This should now be fixed in `autodistill==0.1.7`. Please test and let us know if you run into any issues!

**Comment by jeffreyianwilson** [comment]
Is there not a pip wheel of new release?  When I did a new pull and run pip install . I get an error

D:\work\dev\github\autodistill>pip install .
DEPRECATION: Loading egg at c:\python\python311\lib\site-packages\autodistill-0.1.3-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
Processing d:\work\dev\github\autodistill
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "D:\work\dev\github\autodistill\setup.py", line 12, in <module>
          long_description = fh.read()
                             ^^^^^^^^^
        File "C:\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2399: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by capjamesg** [comment]
There should be. Did you `pip install autodistill==0.1.10`?

**Comment by capjamesg** [comment]
Apologies. We pushed a lot of updates today to resolve some issues with CSV path resolution and to add new command line flags for running `autodistill` in a non-interactive mode. With that said, these changes will probably not have an impact on the issue you reported. Let me investigate with the team and get back to you.

**Comment by capjamesg** [comment]
Hello there! Can you run `pip install --upgrade autodistill` and report back? This issue should now be solved.

**Comment by jeffreyianwilson** [comment]
Upgraded autodistill and ultralytics to compatible version.  Following code returns a circular import error.

```
from autodistill_grounded_sam import GroundedSAM
from autodistill_yolov8 import YOLOv8
from autodistill.detection.caption_ontology import CaptionOntology

# define an ontology to map class names to our GroundingDINO prompt
# the ontology dictionary has the format {caption: class}
# where caption is the prompt sent to the base model, and class is the label that will
# be saved for that caption in the generated annotations
base_model = GroundedSAM(ontology=CaptionOntology({"car": "car"}))

# label all images in a folder called `context_images`
base_model.label(
  input_folder="D:/work/dev/python/segmentation/test/03_split/",
  output_folder="D:/work/dev/python/segmentation/test/03_split/"
)
```
D:\work\dev>C:/Python/Python311/python.exe d:/work/dev/python/labeling/autodistill.py
Traceback (most recent call last):
  File "d:\work\dev\python\labeling\autodistill.py", line 1, in <module>
    from autodistill_grounded_sam import GroundedSAM
  File "C:\Python\Python311\Lib\site-packages\autodistill_grounded_sam\__init__.py", line 1, in <module>
    from autodistill_grounded_sam.grounded_sam import GroundedSAM
  File "C:\Python\Python311\Lib\site-packages\autodistill_grounded_sam\grounded_sam.py", line 17, in <module>
    from autodistill.detection import CaptionOntology, DetectionBaseModel
  File "d:\work\dev\python\labeling\autodistill.py", line 1, in <module>
    from autodistill_grounded_sam import GroundedSAM
ImportError: cannot import name 'GroundedSAM' from partially initialized module 'autodistill_grounded_sam' (most likely due to a circular import) (C:\Python\Python311\Lib\site-packages\autodistill_grounded_sam\__init__.py)

**Comment by jeffreyianwilson** [comment]
OK, when I run this from the root autodistill github repo locally, it works.  Thanks!
