### ISSUE TITLE
Consider to create a dataset folder structure like this...

### ISSUE THREAD

**Issue by alessandropanzieri** [autodistill/autodistill#31]
I have this this Python script, for example:

from autodistill.detection import CaptionOntology
from autodistill_grounded_sam import GroundedSAM

annote = GroundedSAM(ontology = CaptionOntology({"object to detect": "object"}))
annote.label("./object images")

It creates a YOLO suitable dataset folder, but this folder has always an "Instance Segmentation structure".
How can I create a different YOLO dataset folder structure, suitable for Object Detection too? I suppose I cannot...

I think you should consider to create a folder structure like this (suitable both for Instance Segmentation and Object Detection):

![image](https://github.com/autodistill/autodistill/assets/85884872/2f76d9fe-5ccb-468e-b152-46ad2cd371c1)

This image came from Ultralytics Hub documentation (https://docs.ultralytics.com/hub/datasets)
Another problem for dataset folder created by Autodistill is that it is not compliant with Ultralytics Hub...
... So I cannot upload it there :(

I really like this library, it's one of my favorites, so I felt compelled to tell you my opinion, I hope it could help💪

**Comment by SkalskiP** [comment]
Hi, @alessandropanzieri 👋🏻! That dataset structure should be loaded. `autodistill` use [`supervision`](https://github.com/roboflow/supervision) internally and we support the YOLO dataset structure.
