### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2875: illegal multibyte sequence

### ISSUE THREAD

**Issue by yangboning** [autodistill/autodistill#32]
!pip install -q \
autodistill \
autodistill-grounded-sam \
autodistill-yolov8 \
supervision==0.9.0

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\15852\AppData\Local\Temp\pip-install-ev32519r\rf-groundingdino_d3d18c18e7804384a8ed46bce84eecd1\setup.py", line 41, in <module>
          readme = readme_file.read()
                   ^^^^^^^^^^^^^^^^^^
      **UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 2875: illegal multibyte sequence**
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**The attempts I have made are**:
Add **PYTHONIOENCODING="utf-8"** to the system environment variable.

Install the necessary packages: 
**!pip install -q \
opencv-python>=4.6.0 \
supervision \
tqdm \
Pillow>=7.1.2 \\
PyYAML>=5.3.1.**

Still can't fix the problem.

**Comment by lc7457** [comment]
I had the same problem

**Comment by qaz0778899** [comment]
Add encoding = 'UTF-8' in the Setup.py

with open("README.md", "r", encoding='UTF-8') as fh:
    long_description = fh.read()

It works for me.

**Comment by capjamesg** [comment]
This change is now live in `autodistilll==0.1.16`.

**Comment by devadanffefgfh** [comment]
I encountered this problem after pip install autodistill-grounded-sam
Collecting rf-groundingdino (from autodistill-grounded-sam)
  Using cached rf_groundingdino-0.1.2.tar.gz (82 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dan900\AppData\Local\Temp\pip-install-6z_9rpnt\rf-groundingdino_9afb00d728e946a99d306d9260925f5a\setup.py", line 41, in <module>
          readme = readme_file.read()
      UnicodeDecodeError: 'cp950' codec can't decode byte 0xf0 in position 2873: illegal multibyte sequence
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
