### ISSUE TITLE
optimize version?  python, cuda, cudnn

### ISSUE THREAD

**Issue by bulgam** [autodistill/autodistill#37]
What should be the python version and the cuda and cudnn versions to utilize autodistill?

**Comment by capjamesg** [comment]
Hello @bulgam! All `autodistill` models should run on a CUDA GPU by default if one is available. We don't presently have the ability to specify if you want to use GPU or CPU. Rather, if a CUDA GPU is available, it is used; otherwise, the CPU is used.

**Comment by capjamesg** [comment]
I am closing this issue since there have been no more questions. If you need more assistance, feel free to re-open the Issue!
