### ISSUE TITLE
GroundingDINO_SwinT_OGC.py does not exist

### ISSUE THREAD

**Issue by SimonCL17** [autodistill/autodistill#38]
Hi, I have gone through the instructions and seem to run into the following error:

FileNotFoundError: file "/home/simon/.cache/autodistill/groundingdino/GroundingDINO_SwinT_OGC.py" does not exist

I've attached my console output and the file that I am running as well as a copy of my libraries installed. The Autodistil.txt is a .py but github won't let me upload the original .py file.

Any help here would be greatly appreciated.

All the best,

Simon

[ConsoleOutput.txt](https://github.com/autodistill/autodistill/files/12323350/ConsoleOutput.txt)
[CondaEnv.txt](https://github.com/autodistill/autodistill/files/12323351/CondaEnv.txt)
[Autodistil (copy).txt](https://github.com/autodistill/autodistill/files/12323357/Autodistil.copy.txt)

**Comment by capjamesg** [comment]
@SimonCL17 Thank you for your comment! This can happen when the installation process doesn't complete successfully. Please run:

```bash
rm -rf ~/.cache/autodistill/
```

Then, try to set up the model with which you are working again.

**Comment by capjamesg** [comment]
I am closing this Issue since there have been no more comments. If you need more assistance, feel free to reopen the Issue!
