### ISSUE TITLE
could you provide a demo of segGPT autdistill

### ISSUE THREAD

**Issue by ccly1996** [autodistill/autodistill#39]

**Comment by capjamesg** [comment]
@andrew-healey Do you have any demos of SegGPT with `autodistill` that you could share here?

**Comment by andrew-healey** [comment]
You can find a demo [here](https://colab.research.google.com/drive/1ISHSel5Z4n-mV-99g2KkKMwmgfFu-FOQ?usp=sharing)!

**Comment by ccly1996** [comment]
> You can find a demo [here](https://colab.research.google.com/drive/1ISHSel5Z4n-mV-99g2KkKMwmgfFu-FOQ?usp=sharing)!

thank you，i try to run this demo,and the dataset is unavailable？

**Comment by andrew-healey** [comment]
You're right, sorry--how about now?

**Comment by ccly1996** [comment]
i will try again.thank you for your reply😃

---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 09/20/2023 11:34 |
| To | autodistill/autodistill ***@***.***> |
| Cc | ccly1996 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [autodistill/autodistill] could you provide a demo of segGPT autdistill (Issue #39) |

You're right, sorry--how about now?

**Comment by ccly1996** [comment]
> You're right, sorry! How about now?

ooops,i try to download the dataset by the line of your demo,but the website will redirect to my workspace

**Comment by ccly1996** [comment]
> You're right, sorry! How about now?

ooops,i try to download the dataset by the link of demo,but the website redirect to my work space.when i try to download by the code,i got just 2 picures.

**Comment by andrew-healey** [comment]
Two pictures is right! SegGPT requires as few as 1 labelled image to work.

**Comment by ccly1996** [comment]
alright, are there some test pictures available?

---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 09/20/2023 15:08 |
| To | ***@***.***> |
| Cc | ccly1996 ***@***.***>,
State ***@***.***> |
| Subject | Re: [autodistill/autodistill] could you provide a demo of segGPT autdistill (Issue #39) |

Two pictures is intended! SegGPT requires as few as 1 labelled image to work.

**Comment by andrew-healey** [comment]
Sort of--in the "Label your images" section, SegGPT labels 223 unlabelled images.

**Comment by ccly1996** [comment]
but when i click the link,roboflow redirect to my own workspace,i cannot explore your dataset😥

---- Replied Message ----
| From | Andrew ***@***.***> |
| Date | 09/20/2023 15:32 |
| To | autodistill/autodistill ***@***.***> |
| Cc | ccly1996 ***@***.***>,
State ***@***.***> |
| Subject | Re: [autodistill/autodistill] could you provide a demo of segGPT autdistill (Issue #39) |

Sort of--in the "Label your images" section, SegGPT labels 223 unlabelled images.

**Comment by andrew-healey** [comment]
Hm - does [this link](https://universe.roboflow.com/roboflow-4rfmv/parcels-vs.-boxes/dataset/1) work?

**Comment by ccly1996** [comment]
> Sort of--in the "Label your images" section, SegGPT labels 223 unlabelled images.

It worked. Thank you very much for your patient response. Have a nice day

**Comment by andrew-healey** [comment]
You're welcome! This was great feedback. Have a nice day!
