### ISSUE TITLE
How to accelerate training on MPS (Apple M2 chip)

### ISSUE THREAD

**Issue by duckheada** [autodistill/autodistill#44]
Unless I'm missing something, The docs do not show how accelerate training on MPS GPU

**Comment by AlainPilon** [comment]
Same here. I looked at the source code and didnt find anything obvious to enable mps

**Comment by EricZachariaExpression** [comment]
Also looking into this.

**Comment by capjamesg** [comment]
It looks like ultralytics supports MPS for model training (YOLOv8). I can add this into our Autodistill package. I will push a release tomorrow and message here when it is done.

**Comment by capjamesg** [comment]
I have pushed `autodistill-yolov8==0.1.2` which supports providing a `device="mps"` argument in the `train()` call to enable MPS. Let me know if this resolves the issue!

**Comment by AlainPilon** [comment]
You may want to add a note in the doc about this option. If not present, does it uses CPU or automatically goes for the CUDA GPU?

**Comment by AChangXD** [comment]
@capjamesg When you use autodistill to label images, does it also take advantage of MPS as well?

**Comment by capjamesg** [comment]
Good question! Autodistill base models do not support explicitly setting MPS. We have logic that sets your device to either `cpu` or `cuda` depending on whether you have a CUDA-enabled GPU. If you want to see MPS support for a specific base model, let us know and we can investigate whether the change is possible!

**Comment by bartmch** [comment]
> Good question! Autodistill base models do not support explicitly setting MPS. We have logic that sets your device to either `cpu` or `cuda` depending on whether you have a CUDA-enabled GPU. If you want to see MPS support for a specific base model, let us know and we can investigate whether the change is possible.

Hey @capjamesg can you enable mps for GroundedSAM base model?

**Comment by bytesizedwizard** [comment]
Same question here. Base models still run really slow on Mac M2 and performance might be better on MPS.
