### ISSUE TITLE
PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by hebrotem** [autodistill/autodistill#47]
![image](https://github.com/autodistill/autodistill/assets/34936778/94b858eb-f10b-47ce-8fdd-1f16bd865768)

**Comment by vainavinair** [comment]
Hey! i am facing the same issue. Did u find a solution?

**Comment by capjamesg** [comment]
Apologies for missing this! Can you delete the Grounding DINO / Grounded SAM folder in the `~/.cache/autodistill` directory and try again? This error occurs when the installation process was interrupted. If the model weights download does not succeed, Grounding DINO tries to open the incomplete archive, which causes the error.
