### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by computerseelearning2020** [autodistill/autodistill#52]
My issues image
![image](https://github.com/autodistill/autodistill/assets/62364738/1fd33716-386c-40c0-9bac-562c9cf1179f)
My code
![image](https://github.com/autodistill/autodistill/assets/62364738/1d78456b-5b8b-4180-bf17-c64b7425ad4b)
How do I solve this problem?

**Comment by capjamesg** [comment]
Can you delete the Grounding DINO / Grounded SAM folder in the `~/.cache/autodistill` directory and try again? This error occurs when the installation process was interrupted. If the model weights download does not succeed, Grounding DINO tries to open the incomplete archive, which causes the error.

**Comment by capjamesg** [comment]
Hello! Did the comment above help you resolve the issue? If so, please let me know so I can close the Issue!

**Comment by computerseelearning2020** [comment]
> Hello! Did the comment above help you resolve the issue? If so, please let me know so I can close the Issue!

Oh...I still didn't succeed

**Comment by capjamesg** [comment]
Did you get the same error?

**Comment by computerseelearning2020** [comment]
> Did you get the same error?

yes

**Comment by capjamesg** [comment]
What is in your `~/.cache/autodistill` directory?

**Comment by computerseelearning2020** [comment]
[image: image.png][image: image.png]
Sorry, I just saw your message now.
Also, yes, the issue is still not resolved.
This is the content inside my installation file.

James ***@***.***> 於 2023年11月1日 週三 下午7:45寫道：

**Comment by capjamesg** [comment]
I cannot see the images from the email. Would you mind uploading them to the GitHub thread directly?

**Comment by computerseelearning2020** [comment]
Ok

James ***@***.***> 於 2023年11月3日 週五 下午8:31 寫道：

**Comment by computerseelearning2020** [comment]
![image (1)](https://github.com/autodistill/autodistill/assets/62364738/b8b07e6d-7113-4b78-bfb5-00eac468bd04)
![image](https://github.com/autodistill/autodistill/assets/62364738/deb04321-d596-4a58-b666-7ba82ed64e0c)

**Comment by capjamesg** [comment]
Can you list the `~/.cache/autodistill/` directory. It looks like the image above shows the `autodistill` module directory, which does not contain the information I need to investigate this further.

**Comment by computerseelearning2020** [comment]
Sorry, the computer was unavailable before.
I give it to you now.
I hope the following pictures have what you want to confirm.
[image: image.png]

James ***@***.***> 於 2023年11月21日 週二 下午8:24寫道：

**Comment by capjamesg** [comment]
I don't see an image in your message. It looks like emailing images with GitHub might not be working properly. Can you try again by uploading your image through the GitHub web interface?

**Comment by computerseelearning2020** [comment]
ok
Sorry, I forgot.

James ***@***.***> 於 2023年11月29日 週三 下午5:26寫道：

**Comment by computerseelearning2020** [comment]
![image](https://github.com/autodistill/autodistill/assets/62364738/0bf794c7-30b1-4808-b0e1-3c0c380fab89)

**Comment by R3xpook** [comment]
seems like if you using groundingdino before and than try to use grounded SAM it gives this error

**Comment by computerseelearning2020** [comment]
OH~I see,
Thank you


R3xpook ***@***.***> 於 2024年1月4日 週四 上午11:45寫道：

**Comment by capjamesg** [comment]
Is this issue still causing problems? If not, I will close it in the next few days.

**Comment by capjamesg** [comment]
I am going to close this issue, but we can re-open it if further assistance is required.
