### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not ClassificationDataset

### ISSUE THREAD

**Issue by ccly1996** [autodistill/autodistill#53]
When I use autodistill-clip for image classification, the runtime prompts this error:TypeError: expected str, bytes or os.PathLike object, not ClassificationDataset
<img width="833" alt="image" src="https://github.com/autodistill/autodistill/assets/39228103/c27ead78-0d6e-43a9-9ea7-2f58919ab7a3">

**Comment by capjamesg** [comment]
@ccly1996 Can you share the code that caused this issue?

**Comment by cisco-silva** [comment]
I have the same issue. Please find below the code:

```
from autodistill.detection import CaptionOntology
from autodistill_clip import CLIP

ontology = CaptionOntology({
    "hand holding primary product or packaged item": "hand_with_product",
    "hand not holding primary product or packaged item": "hand_without_product"
})

imgs_dir_path = '/home/images'
dataset_dir_path = '/home/dataset'

base_model = CLIP(ontology=ontology)
dataset = base_model.label(
    input_folder=imgs_dir_path,
    extension=".jpg",
    output_folder=dataset_dir_path)
```

**Comment by muhammad-usama-aleem** [comment]
I got the similar error. I am following a tutorial notebook from roboflow which uses autodistill. 

My code:

from autodistill_clip import CLIP
```
from autodistill.detection import CaptionOntology
from autodistill_yolov8 import YOLOv8
import supervision as sv
import roboflow
import cv2
import os


base_model = CLIP(ontology=CaptionOntology({"damaged sign": "damaged sign", "sign": "sign"}))

base_model.label(input_folder="./Damaged-Signs-Multi-label-3/train", output_folder="./dataset")

```

![error Image](https://github.com/autodistill/autodistill/assets/56190389/22e041d1-8edc-41b5-a9e6-b7310e571569)

After completing the processing on all the images, it gives this error while splitting the images in test/train.

**Comment by muhammad-usama-aleem** [comment]
I was looking at the source of the autodistill's classification helper function, which is causing this error. `split_data` function is expecting `base_dir` which should be path(string), but currently dataset, an object is being passed into it.

**Comment by muhammad-usama-aleem** [comment]
@capjamesg I just opened a PR trying to resolve this issue. Would love to hear your thoughts about it.

**Comment by capjamesg** [comment]
Will review!

**Comment by cobaltautomationdev** [comment]
.venv\Lib\site-packages\autodistill\classification\classification_base_model.py 
train_cs, test_cs = split_data(dataset, split_ratio=0.7) 
changed to 
train_cs, test_cs = dataset.split(split_ratio=0.7, shuffle=True)
test_cs, valid_cs = test_cs.split(split_ratio=0.5,, shuffle=True)
