### ISSUE TITLE
Error with OWLVit

### ISSUE THREAD

**Issue by shersoni610** [autodistill/autodistill#54]
Hello,

 While using OWLVit as a base model, I get the following error:

RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Comment by capjamesg** [comment]
@shersoni610 Thank you for creating this Issue! Can you share the code you used?

**Comment by shersoni610** [comment]
Hello, It is the same code from the autodistill webpage. No changes.

**Comment by mrgares** [comment]
This issue is solved in this [PR](https://github.com/autodistill/autodistill-owl-vit/pull/5). It is just not merged yet.
