### ISSUE TITLE
SAM-Clip model producing many boxes

### ISSUE THREAD

**Issue by csv610** [autodistill/autodistill#55]
Hello,

When I run SAM Clip model, it printouts several box and I am sure that it should detect only 1-2 boxes in the image. Why it is dumping so many boxes?

Labeling People/a-good-person.jpg:   2%|▌                              | 2/115 [00:12<10:39,  5.66s/it]tensor([[0.5508, 0.4495]], device='cuda:0', dtype=torch.float16)
tensor([[0.0610, 0.9390]], device='cuda:0', dtype=torch.float16)
tensor([[0.1097, 0.8901]], device='cuda:0', dtype=torch.float16)
tensor([[0.6001, 0.3999]], device='cuda:0', dtype=torch.float16)
tensor([[0.5659, 0.4341]], device='cuda:0', dtype=torch.float16)
tensor([[0.1968, 0.8032]], device='cuda:0', dtype=torch.float16)
tensor([[0.3960, 0.6040]], device='cuda:0', dtype=torch.float16)
tensor([[0.1442, 0.8560]], device='cuda:0', dtype=torch.float16)
tensor([[0.1442, 0.8560]], device='cuda:0', dtype=torch.float16)
tensor([[0.0656, 0.9346]], device='cuda:0', dtype=torch.float16)
tensor([[0.0550, 0.9448]], device='cuda:0', dtype=torch.float16)
tensor([[0.0676, 0.9326]], device='cuda:0', dtype=torch.float16)
tensor([[0.2338, 0.7661]], device='cuda:0', dtype=torch.float16)
tensor([[0.0415, 0.9585]], device='cuda:0', dtype=torch.float16)
tensor([[0.1294, 0.8706]], device='cuda:0', dtype=torch.float16)
tensor([[0.1009, 0.8989]], device='cuda:0', dtype=torch.float16)
tensor([[0.2095, 0.7905]], device='cuda:0', dtype=torch.float16)
tensor([[0.1009, 0.8989]], device='cuda:0', dtype=torch.float16)
tensor([[0.2120, 0.7881]], device='cuda:0', dtype=torch.float16)
tensor([[0.0839, 0.9160]], device='cuda:0', dtype=torch.float16)
tensor([[0.1067, 0.8931]], device='cuda:0', dtype=torch.float16)
tensor([[0.0726, 0.9272]], device='cuda:0', dtype=torch.float16)
tensor([[0.4341, 0.5659]], device='cuda:0', dtype=torch.float16)
tensor([[0.4570, 0.5430]], device='cuda:0', dtype=torch.float16)
tensor([[0.1113, 0.8887]], device='cuda:0', dtype=torch.float16)
tensor([[0.0440, 0.9561]], device='cuda:0', dtype=torch.float16)
tensor([[0.0637, 0.9365]], device='cuda:0', dtype=torch.float16)
tensor([[0.0284, 0.9717]], device='cuda:0', dtype=torch.float16)
tensor([[0.0706, 0.9292]], device='cuda:0', dtype=torch.float16)
tensor([[0.1208, 0.8789]], device='cuda:0', dtype=torch.float16)
tensor([[0.0815, 0.9185]], device='cuda:0', dtype=torch.float16)
tensor([[0.4111, 0.5889]], device='cuda:0', dtype=torch.float16)
tensor([[0.1348, 0.8652]], device='cuda:0', dtype=torch.float16)
tensor([[0.1225, 0.8774]], device='cuda:0', dtype=torch.float16)
tensor([[0.1500, 0.8501]], device='cuda:0', dtype=torch.float16)
tensor([[0.1294, 0.8706]], device='cuda:0', dtype=torch.float16)
tensor([[0.1097, 0.8901]], device='cuda:0', dtype=torch.float16)
tensor([[0.1919, 0.8081]], device='cuda:0', dtype=torch.float16)
tensor([[0.1176, 0.8823]], device='cuda:0', dtype=torch.float16)
tensor([[0.1329, 0.8672]], device='cuda:0', dtype=torch.float16)
tensor([[0.0610, 0.9390]], device='cuda:0', dtype=torch.float16)
tensor([[0.2173, 0.7827]], device='cuda:0', dtype=torch.float16)
tensor([[0.1329, 0.8672]], device='cuda:0', dtype=torch.float16)
tensor([[0.0685, 0.9316]], device='cuda:0', dtype=torch.float16)
tensor([[0.0666, 0.9336]], device='cuda:0', dtype=torch.float16)
tensor([[0.1646, 0.8354]], device='cuda:0', dtype=torch.float16)
tensor([[0.0851, 0.9150]], device='cuda:0', dtype=torch.float16)
tensor([[0.3811, 0.6187]], device='cuda:0', dtype=torch.float16)
tensor([[0.1113, 0.8887]], device='cuda:0', dtype=torch.float16)
tensor([[0.3008, 0.6992]], device='cuda:0', dtype=torch.float16)
tensor([[0.0474, 0.9526]], device='cuda:0', dtype=torch.float16)
tensor([[0.1144, 0.8857]], device='cuda:0', dtype=torch.float16)

**Comment by capjamesg** [comment]
Hello! Thank you for opening this Issue. What are you trying to predict with SAM-CLIP?

**Comment by csverma610** [comment]
Thank you very much. Are you planning to remove it and update the pip.

**Comment by capjamesg** [comment]
We have replaced the autodistill-sam-clip module with the new model combination API. See the [autodistill-sam-clip](https://github.com/autodistill/autodistill-sam-clip) README for instructions on how to use the new module. I encourage you to try the new model combination API outlined in the `autodistill-sam-clip README. The new API is more flexible and should not encounter the issue you pointed out above. Let me know if you have any questions!
