### ISSUE TITLE
Documentation update may be needed

### ISSUE THREAD

**Issue by apiszcz** [autodistill/autodistill#59]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar bug report.

### Bug

```
Current:

https://docs.autodistill.com/
autodistill images --base-model="grounding_dino" --target-model="yolov8" --ontology '{"prompt": "label"}' --output-folder ./dataset

Suggested update
autodistill images --base="grounding_dino" --target="yolov8" --ontology '{"prompt": "label"}' --output ./dataset

```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
Thank you for reporting this Issue! We appreciate your contribution!

I have made the requisite amendments to the `autodistill` documentation and `README`. I will re-build the docs site so that the changes appear at `autodistill.roboflow.com`.
