### ISSUE TITLE
fine-tune models to specific classes

### ISSUE THREAD

**Issue by kobic8** [autodistill/autodistill#6]
looks promising! so if I understand correctly - there are two phases: (1) auto-label an image dataset, something that you already showed in the G-SAM previous video (2) split the dataset to test/train/val and build a CV model with YOLO-8
q1: since auto-labeling is not 100% fullproof, what about the human in the loop? 
q2: what if the base model doesn't recognize the labels (name of specific boats I have in a marine dataset), how can I fine-tune it? so the model will find a boat, but will also "know" the brand of the boat

**Comment by yeldarby** [comment]
Good questions. Both of these are areas we’re actively working on.

> so if I understand correctly - there are two phases

That’s correct.

> since auto-labeling is not 100% fullproof, what about the human in the loop?

We have plans to make this much more seamless, but for now you can drop the dataset into Roboflow (it can import and parse the format). 

Right now it’s just as easy from that point to go down the “normal” training flow as it would be to bring it back into autodistill. But that will get much better soon with a native integration.

> what if the base model doesn't recognize the labels (name of specific boats I have in a marine dataset), how can I fine-tune it? so the model will find a boat, but will also "know" the brand of the boat

There may be some prompt engineering you can do (we’re working on tooling to make it easier to experiment with prompts) but this is largely a limitation of the base models at the moment (and autodistill may not yet be a good solution for this problem yet). It will get better with time as more powerful Base Models come out.

We are also working on allowing you to augment the Base Models with supervised models (for example use GroundedSAM to find and segment the boats, but use a fine-tuned ViT to classify them).
