### ISSUE TITLE
Altering Box Threshold and Text Threshold Values 

### ISSUE THREAD

**Issue by sivaji123256** [autodistill/autodistill#66]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question
Hi @yeldarby @hariag @SkalskiP @andrew-healey 
Is there any way to play with Box_threshold and text_threhsold while generating datasets for our custom datasets? When I directly used groundingDINO ,I have flexibility to use and change those values as per our requirements on our custom datasets.

**Comment by capjamesg** [comment]
Hello there! You can set the box and text thresholds when you instantiate the model:

```python
model = GroundingDINO(ontology=CaptionOntology({}), box_threshold=0.5, text_threshold=0.5)
```

The default values are:

- `box_threshold`: 0.35
- `text_threshold`: 0.25

**Comment by capjamesg** [comment]
I am going to close this Issue. Let me know if you have any more questions!
