### ISSUE TITLE
Use labelled data to improve labeling

### ISSUE THREAD

**Issue by adbcode** [autodistill/autodistill#69]
Say I have labeled some images in a format of one of the target models (e.g. YOLOv8).

Is it possible to use them to assist the automatic labeling by the base model?

In my use case, the classes to label (for instance segmentation) are not easy to describe in the ontology, which results in poor out-of-box performance.

**Comment by capjamesg** [comment]
@adbcode Labeling using any of the target models is not currently supported in Autodistill. We are working on an extension that lets you use models on Roboflow Universe to label data. This will be released in the next few days. I will message here when this is available. With this setup, you can [upload your model weights to Roboflow](https://docs.roboflow.com/deploy/upload-custom-weights) then use them in Autodistill.

If you are interested in adding labeling from a target model directly, feel free to file a PR!

**Comment by adbcode** [comment]
> @adbcode Labeling using any of the target models is not currently supported in Autodistill. We are working on an extension that lets you use models on Roboflow Universe to label data. This will be released in the next few days. I will message here when this is available. With this setup, you can [upload your model weights to Roboflow](https://docs.roboflow.com/deploy/upload-custom-weights) then use them in Autodistill.
> 
> If you are interested in adding labeling from a target model directly, feel free to file a PR!

The ability to do something similar locally would be great.

Anyways I look forward to this approach!

**Comment by capjamesg** [comment]
You can now use Roboflow Universe models to label data: https://github.com/autodistill/autodistill-roboflow-universe

**Comment by jamesheatonrdm** [comment]
Hi @capjamesg I see this repository, but I am unsure how to use this to use labelled data as a prompt for the base model.

I am also facing the same issue as @adbcode where my objects are unique and hard to describe using CaptionOntology. I was wondering if the was some sort of similar bounding box ontology where we could provide bounding boxes of our target classes as prompts for automatic labelling.
