### ISSUE TITLE
how to convert created dataset to coco detection yolo format?

### ISSUE THREAD

**Issue by hlacikd** [autodistill/autodistill#7]
I am using  GroundedSAM as base model to label all images , i have only 1 class.
Resulting dataset contains many points of identified labels (probably for segmentation usage as well).

However I need to convert this dataset to coco detection format (class and 4 points) to use it outside of auto distill.
Is it possible?

**Comment by yeldarby** [comment]
It’s saved in YOLO format in the `output_folder` directory you pass to your BaseModel by default. It uses the YOLO polygon txt format supported by most modern YOLO models if your BaseModel predicts polygons (like GroundedSAM does), or the YOLO box format if your BaseModel predicts boxes (like GroundingDINO, DETIC, and OWL-ViT do).
