### ISSUE TITLE
SAM Clip confidence level?

### ISSUE THREAD

**Issue by shersoni610** [autodistill/autodistill#72]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question

Hello, 

I was wondering if the following line is correct in the code:

def predict(self, input: str, confidence: int = 0.5) -> sv.Detections:

Shouldn't this value be float instead of int?

Thanks

**Comment by capjamesg** [comment]
@artyaltanzaya Should the confidence value be an integer? I think CLIP returns raw values from 0-1 that we don't post-process, looking at the code in our implementation.

**Comment by capjamesg** [comment]
@shersoni610 We have replaced the `autodistill-sam-clip` module with the new model combination API. See the [autodistill-sam-clip](https://github.com/autodistill/autodistill-sam-clip) README for instructions on how to use the new module.
