### ISSUE TITLE
[Question] GPU Utilization

### ISSUE THREAD

**Issue by AChangXD** [autodistill/autodistill#8]
Is it normal for GPU utililization rate to be close to 0%? I'm trying to label a folder of images and it seems like the computation is almost 100% done on the CPU. Is there a setting I can change or a param I have to specify to allow GPU acceleration?

**Comment by AChangXD** [comment]
GroundSAM, the one that was listed in the Quick Start. 
`# define an ontology to map class names to our GroundingDINO prompt
# the ontology dictionary has the format {caption: class}
# where caption is the prompt sent to the base model, and class is the label that will
# be saved for that caption in the generated annotations
base_model = GroundedSAM(ontology=CaptionOntology({"beverage containers": "container"}))

# label all images in a folder called `context_images`
base_model.label(
  input_folder=r"C:\Users\markc\Desktop\bottleCounterData",
  output_folder=r"C:\Users\markc\Desktop\labeled_output"
)
`

**Comment by yeldarby** [comment]
It was able to utilize the GPU for most layers when I tested. But I’ve never used Windows so not sure what you might need to do there (if anything).

How long per image is inference taking? With GPU on an A100 it was taking about 0.2 seconds for me. On CPU it was taking about 17 seconds per image. So it should be pretty obvious whether it’s using GPU or not.

**Comment by AChangXD** [comment]
Turns out Pytorch was unintentionally using CPU due to a CUDA versioning issue. On CPU it took ~19 seconds per image (255 images took about an hour and 20 minutes to complete), on a laptop 3080 Ti it takes about 1s per image. If anyone runs into this issue you can double check if PyTorch is using GPU by:

`torch.cuda.is_available()`
