### ISSUE TITLE
[Question] Extracting prompt for feature / actions

### ISSUE THREAD

**Issue by chaudhryfaisal** [autodistill/autodistill#9]
it is possible to extract features or actions from an image? like
- instead of a person  -> a person that is sitting or walking 
- instead of the player/person -> player who is kicking the ball
- instead of bottle -> bottle that has fallen / sideway

**Comment by yeldarby** [comment]
Yes, you should be able to do this in your Ontology. Whether the BaseModels will be good enough to differentiate between them is impossible to tell without some experimentation and prompt engineering though!

Give it a try and let us know how it goes and which BaseModel seems to do best.

**Comment by chaudhryfaisal** [comment]
could you please share some pointers on what base models would be good for this? 
it is just changing the Ontology and running tests? CaptionOntology({"sitting person": "kicking"}) or run first extract person than sitting/kicking. 

Any helpful links to find out what kind of prompts base models support? 

Thank you

**Comment by yeldarby** [comment]
I don't yet have a great intuition for this -- it'll take some trial and error, but once you've done more experimentation please report back & we can all learn together!

**Comment by SkalskiP** [comment]
Hi, @chaudhryfaisal 👋🏻 ! To answer your original question. I experimented with prompts like that, and it worked, but like @yeldarby, there is no way to tell upfront. You need to test on your specific use case. You can read my blogs [here](https://blog.roboflow.com/grounding-dino-zero-shot-object-detection/) and [here](https://blog.roboflow.com/enhance-image-annotation-with-grounding-dino-and-sam/) to learn more. Here is an example of successful prompt engineering. 

![1_lsJoC2TZooYwv4-QAmXjLQ](https://github.com/autodistill/autodistill/assets/26109316/cdcdc561-ae20-4083-8ce8-d3e1598b7d04)
