### ISSUE TITLE
No response on issue 90

### ISSUE THREAD

**Issue by andysingal** [autodistill/autodistill#91]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar bug report.

### Bug

Shared the issue in ticket https://github.com/autodistill/autodistill/issues/90

### Minimal Reproducible Example

https://github.com/autodistill/autodistill/issues/90

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by capjamesg** [comment]
Correspondence regarding your issue will be kept in #90.
