### ISSUE TITLE
About dowanload of milk‘s data

### ISSUE THREAD

**Issue by Fackyhub** [autodistill/autodistill#95]
### Search before asking

- [X] I have searched the Autodistill [issues](https://github.com/autodistill/autodistill/issues) and found no similar feature requests.

### Question

so，i can't download it by used wget。how can i get it by others way,can you share mike's data download link.
I operate by windows

**Comment by Fackyhub** [comment]
I operate by windows

**Comment by capjamesg** [comment]
You can download the video from here: https://media.roboflow.com/supervision/video-examples/milk-bottling-plant.mp4

**Comment by Fackyhub** [comment]
ok，tanks！
